apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-deployment
  labels:
    app: pet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet
  template:
    metadata:
      labels:
        app: pet
    spec:
      containers:
      - name: petclinic
        image: becomedevops/petclinics:latest
        ports:
      - containerPort: 8060
        
---

apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
spec:
  selector:
    app: pet
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8060
  
  type: LoadBalancer
      
